version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ../:/app
    command: bash -lc "pip install -r requirements.txt && uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./dev.db
